name: Tag Pachi
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Tag pachiu
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "@pachicodes vem cรก"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
